<a href="https://colab.research.google.com/github/natjak/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)


### <a name='a1'></a> Podstawy

In [1]:
# importujemy
import numpy as np
# sprawdzamy wersję
np.__version__

'1.21.6'

In [ ]:
# klasy w numpy
print(dir(np))

# czasem warto zamykać okna, żeby nie zapisywać w pamięci githuba wyników

In [ ]:
#HELP!
help(np.array)

1D Array

In [4]:
# wielowymiarowa tablica o jednorodnych elementach
# wymiary tablicy zazwyczaj nazywamy osiami (axis)
x = np.array([1, 3]) # podajemy listę elementów do tablicy
x

array([1, 3])

In [5]:
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

In [7]:
# zobaczmy atrybuty naszej tablicy (wymiary)
x.ndim

1

In [8]:
# a kształt?
x.shape # podany jako tuple, mamy 2 elementy

(2,)

In [10]:
# atrybut size, który poda nam liczbę elementów tablicy
x.size

2

In [9]:
# tym naszych danych
x.dtype

dtype('int64')

In [11]:
# lista z trzech floatów
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [12]:
x.dtype

dtype('float64')

2D Array

In [13]:
#dwuwymiarowe tablice, czyli macierz
x = np.array([[1, 2], [-3, 1]]) # listy w listach
x

array([[ 1,  2],
       [-3,  1]])

In [14]:
# liczba wymiarów
x.ndim

2

In [15]:
# kształt
x.shape

(2, 2)

In [18]:
# macierz/tablica 2 na 3
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [19]:
x.shape

(2, 3)

3D Array

In [20]:
# 3-wymiarowa, jeszcze mocniej zagnieżdżona tablica
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [21]:
x.ndim

3

In [22]:
x.shape

(3, 2, 3)

### <a name='a2'></a> Typy danych

In [23]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [24]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [25]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [26]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [28]:
# a co to jest ta liczba złożona?
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [29]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

In [30]:
A

array([1, 2, 3])

In [31]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [32]:
# czyli, że co?
A

array([ True, False])

In [33]:
# konkretny typ danych (np. 8-bitowa liczba)
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [34]:
A

array([ 24, 120, -26], dtype=int8)

### <a name='a3'></a> Tworzenie tablic

In [ ]:
# ZEROS - czy brzmi znajomo? MATLAB pozdrawia
np.zeros(shape=(4, 10)) # wiersze na kolumny

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
# przekształćmy to na liczby całkowite
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

A po co to wszystko? No gdybyśmy chcieli stworzyć mapkę zdjęcia (albo takiego sygnału EEG (64 elektrody x 250 punktów)), to łatwiej jest z góry zdefiniować taki rozmiar i sprawdzać, czy wszystko się zgadza :)

In [36]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
# a da się inaczej? Co jeśli chce mieć tam 4?
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [40]:
# generowane 10 próbek od 0 (czyli nie do 10!)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [42]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [44]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [45]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [46]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [50]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [51]:
A + B

array([6, 0, 7, 4])

In [52]:
A - B

array([0, 2, 1, 0])

In [53]:
A * B

array([ 9, -1, 12,  4])

In [54]:
A / B # a co gdyby w tablicy było 0?

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [55]:
np.add(A, B)

array([6, 0, 7, 4])

In [56]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [57]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [58]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [59]:
A + 3 #dodajemy 3 do każdego elementu tablicy A

array([6, 4, 7, 5])

In [60]:
2 * A

array([6, 2, 8, 4])

In [61]:
A + 3*B

array([12, -2, 13,  8])

In [62]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [63]:
X * Y

array([[6, 0],
       [2, 0]])

In [64]:
# mnożenie z algebry liniowej, mnożenie macierzowe (wiersz * kolumna, wiersz * kolumna)
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [65]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [66]:
Y.dot(X) # mnożenie macierzy nie jest naprzemienne, czyli w zależności od tego, co mnożymy przez co - otrzymujemy inny wynik

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y # symbol @ (at) daje to samo

array([[  3,   6],
       [-12,   0]])

### <a name='a5'></a>  Generowanie liczb pseudolosowych

In [67]:
np.random.seed(0) # ziarno losowania, dba o to, żeby za każdym razem dostać ten sam wynik losowania

In [71]:
np.random.randn() # losowa liczba z rozkładu normalnego

2.240893199201458

In [72]:
np.random.randn(10) # 10 liczb z rozkładu normalnego

array([ 1.86755799, -0.97727788,  0.95008842, -0.15135721, -0.10321885,
        0.4105985 ,  0.14404357,  1.45427351,  0.76103773,  0.12167502])

In [73]:
np.random.randn(10, 4) # tablica 10x4 liczb z rozkładu normalnego

array([[ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028],
       [-0.89546656,  0.3869025 , -0.51080514, -1.18063218]])

In [74]:
np.random.rand() # rozkład jednostajny na przedziale (od 0 do 1)

0.8209932298479351

In [75]:
np.random.rand(10)

array([0.09710128, 0.83794491, 0.09609841, 0.97645947, 0.4686512 ,
       0.97676109, 0.60484552, 0.73926358, 0.03918779, 0.28280696])

In [76]:
np.random.rand(10, 2)

array([[0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609],
       [0.18319136, 0.58651293]])

In [84]:
np.random.randint(10) # liczba całkowita z przedziału od 0 do 10

8

In [85]:
#możemy podać parametry (przedział)
np.random.randint(low=10, high=101)

82

In [86]:
np.random.randint(low=10, high=101, size=10)

array([29, 82, 36, 76, 62, 77, 71, 24, 14, 77])

In [87]:
# losowy element z listy
np.random.choice([4, 2, 1, 3, 5])

3

In [88]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [89]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.random.shuffle(data) # tasowanie

In [91]:
data

array([2, 4, 3, 9, 1, 5, 7, 0, 8, 6])

### <a name='a6'></a> Podstawowe funkcje

In [92]:
np.exp(1) #eksponent - stała Eulera

2.718281828459045

In [93]:
np.sqrt(9) # pierwiastek kwadratowy

3.0

In [98]:
np.all([2, 3, 0]) #bada, czy zwraca wartość logiczną True czy False. Jeśli każda to True - zwróci True, jeśli chociaż jedna to False - zwróci False

False

In [99]:
np.any([0, 0, 1])

True

In [97]:
bool(1.3)

True

In [100]:
A = np.random.rand(5)
A

array([0.50132438, 0.95608363, 0.6439902 , 0.42385505, 0.60639321])

In [102]:
np.argmax(A) #zwróci nam indeks największej wartości

1

In [103]:
A[np.argmax(A)] # zwróci faktycznie największą wartość w tablicy

0.9560836347232239

In [104]:
np.argmin(A) #zwróci nam nam indeks wartości najmniejszej

3

In [105]:
np.argsort(A) #sortuje elementy i zwraca ich indeks (rosnąco)

array([3, 0, 4, 2, 1])

In [106]:
np.max(A) #największa wartość

0.9560836347232239

In [108]:
np.min(A) #najniższa wartość

0.4238550485581797

In [109]:
np.mean(A)

0.6263292957131336

In [110]:
np.median(A)

0.6063932141279244

In [111]:
np.std(A)

0.18224671639823387

###  <a name='a7'></a> Indeksowanie, Wycinanie

In [112]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:] <- to wszystko, to operowanie na indeksach

In [ ]:
A[2]

2

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[[0, 2]]

array([0, 2])

In [ ]:
A[-1]

19

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [113]:
A = A.reshape(4, 5) #zmieniamy układ tablicy
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [115]:
A[:,-2] # wszystkie wiersze z przedostatniej kolumny

array([ 3,  8, 13, 18])

In [116]:
A[3,:] # wszystkie kolumny z 4 wiersza

array([15, 16, 17, 18, 19])

In [117]:
A[1:3, 1:4] # pierwszy i drugi wiersz, kolumny druga, trzecia i czwarta

array([[ 6,  7,  8],
       [11, 12, 13]])

In [118]:
A[1, 2] = 14 # podmieńmy jakiś element
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [119]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [120]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [122]:
for row in A:
    print(row[0])

0
5
10
15


In [123]:
for row in A:
    print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [124]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [125]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [126]:
A.shape

(4, 5)

In [127]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [128]:
A.ravel() # wracamy do postaci płaskiej, jednowymiarowej

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [130]:
A.T # zamieniamy miejscami kolumny i wiersze

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [132]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [133]:
A > 0 # sprawdźmy, w których miejscach mamy wartości ujemne

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [135]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [136]:
A[np.bitwise_and(A > -5, A < 5)] # zwracamy to jako jedną listę

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A < -5, A > 5) # warunek OR zamiast AND

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])